---
driver:
  name: gce
  project:      <%= ENV['GCP_PROJECT'] %>
  zone:         <%= ENV['GCP_ZONE'] %>
  email:        <%= ENV['GCP_EMAIL'] %>
  machine_type: n1-standard-1
  service_account_scopes:
  - servicecontrol
  - service.management.readonly
  - logging.write
  - monitoring.write
  - trace.append
  - devstorage.read_only
    
transport:
  username: <%= ENV['GCP_USER'] %>
  ssh_key:  <%= ENV['GCP_SSH_KEY'].tr('\\','/') %>

provisioner:
  name: chef_zero
  product_name: chef
  chef_license: accept

verifier:
  name: inspec

platforms:
<% %w(15 16).each do |chef_ver| %>
  <% %w(2012-r2 2012-r2-core 2016 2016-core 2019 2019-core 2019-for-containers 2019-core-for-containers).each do |win_ver| %>
  - name: <%= "win-#{win_ver}-#{chef_ver}" %>
    driver_config:
      image_project: windows-cloud
      image_family: windows-<%= win_ver %>
      disk_size: 80
    provisioner:
      product_version: <%= chef_ver %><% end %>
<% end %>

suites:
  - name: hs94
    run_list:
      - recipe[hana-studio]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
      sap:
        hanastudio: "https://storage.googleapis.com/cookbook_dev_share/opensource_test_djl/win/rev_1_00_094.zip"
  - name: sar
    run_list:
      - recipe[hana-studio]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
      sap:
        sapcar: "https://storage.googleapis.com/cookbook_dev_share/opensource_test_djl/SAPCAR_721-20010453.EXE"
        hanastudio: "https://storage.googleapis.com/cookbook_dev_share/opensource_test_djl/win/IMC_STUDIO2_112_7-80000323.SAR"
